### ISSUE TITLE
Are there any guild to build/compile the Stremio OS for rpi 4b?

### ISSUE THREAD

**Issue by tonyho** [Stremio/stremio-os-rpi#1]
I want to buld the os myself, are there any guide for it?

**Comment by jaruba** [comment]
as mentioned in the official blog post about this project: https://blog.stremio.com/stremio-os-is-now-available-for-raspberry-pi-5-4/

> This release uses [LineageOS](https://lineageos.org/) v21 (based on Android TV 14, custom build by [Kostakang](https://konstakang.com/))

You can go to Konstakang's website to download his build, but as far as I know his projects are not open source, so you cannot build either his project or Stremio OS unless he makes them open source.
